import type { Metadata } from "next";
import { Bai_Jamjuree, Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components";
import { Providers } from "./Providers";
import { NavMobile } from "@/components/navbar/NavMobile";

const inter = Inter({ subsets: ["latin"] });
const baijamjuree = Bai_Jamjuree({subsets: ["latin"], weight: ["700", "600", "500", "400", "300", "200"]})

export const metadata: Metadata = {
  title: "Diarc Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <link rel="shortcut icon" href="/favicon/favicon.ico" />
      <body className={baijamjuree.className}>
        <Providers>
          <Nav/>
          <NavMobile/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
